### PR TITLE
Add select, populate, limit, sort to reverse-population query

### PR DESCRIPTION
**Pull request by zoltanradics**
Just added select, populate, limit, sort to reverse-population query becouse i found it will be more helpful to control what you really want to reverse-populate

### CODE REVIEW

**Comment by zoltanradics** [comment]
Thanks, PR has gone. Greetings from Budapest!

**Comment by s-taylor** [comment]
Thanks so much for the PR. I'll hopefully get it merged and up on npm within a week. I want to add a few tests to cover the new query options and also I noticed that "select" is a little dangerous as if you don't include the necessary id for the model you are populating into it will blow up.

There are a few ways that could be solved...
- I could just always append the required id to the select that was input 
- I could error out if the user doesn't include the required id in their select
- A final and much more complicated option would be to add the id to the select, and then after the population completes remove the id from all the nested models. Probably not worth doing though!

**Comment by zoltanradics** [comment]
I will take a look into it today and get back to you!

**Comment by s-taylor** [comment]
Hey mate,

I've finally gotten your changes integrated and made available on NPM. I added tests for the new functionality so confident it's all working now.  Apologies this took so long, I've been tied up with many other things!

Select required some extra care as if someone excluded the id field needed for the populate it would break. Basically I went with option 1 above.

I decided to remove limit after some consideration as I felt it wouldn't actually be useful. Because this solution only runs a single query, you're limiting the total results returned. It's not a per model limit (that might have been useful). So because "limit" would affect your results in a fairly arbitrary way I decided not to go with it. Open to reconsider if you think it's useful though.

Sort also actually sorts the entire result set before the results are allocated to their related models, but this works fine because the allocation is sequential and you still do end up with sorted models after the allocation.

Anyway, thanks for your contribution and I've added you to the readme to say thank!

Cheers,
Simon

**Comment by zoltanradics** [comment]
Hey Simon!

Great to hear that it's out. I might will workout a solution to take care about select() as well.
Thanks for letting me know and for the credit.

Cheers,
Zoltan

**Comment by s-taylor** [comment]
I did get select to work, I just ensured that even if you try to remove the id field that's needed it gets added back in automatically. But the field will then be visible even though you didn't ask for it. Not a big deal I don't think though.

**Pull request merged**
