### PR TITLE
Adds support for populating against fields other than _id

### PR DESCRIPTION
**Pull request by ablankenship10**
- Support for a new non-required option 'indexField'
- Added .idea directory to .gitignore for anyone using Webstorm editing this project
- Updated README with instructions on using 'indexField' option.

### CODE REVIEW

**Comment by s-taylor** [comment]
Thanks for PR! I'll have a review and try get this merged and then released. If you could possibly add a test using the indexField that would help me out ^_^

**Comment by ablankenship10** [comment]
I tried to install dev dependencies and it started an install loop that never finished 0.o Don't think i will be able to do this, at least today. You could try this:

For a test you would want to add a field to the Posts with something like the Author's First Name, and use these opts:

```
{
        modelArray: authors,
        mongooseModel: Post,
        arrayPop: false,
        idField: 'authorFirstName',
        indexField: 'firstName',
        storeWhere: 'author'
};
```

For your test case it doesn't really add any value but for my case I was storing 2 different types of documents using upserts at the same time and never knew the _id of the previous document, so I used a string key instead that is the same on both documents. It's working great! Thanks for the module.

**Comment by ablankenship10** [comment]
Hey is there anyway to get this merged soon? Trying to deploy our code to our dev server and npm is having issues pulling from Git repos when using our deploy system. Being in npm itself would fix that problem right away.

**Comment by s-taylor** [comment]
I'll see if I can get this merged and released for you today.

**Comment by s-taylor** [comment]
Before going ahead with this I just want to be sure I understand the problem definition. Is the below an example of what you're talking about?

An Authors has many Blogs.

Author doc:

```
_id: “uuiduuiduuiduuid"
name: “Dave”
blogs: [“Some interesting things I think”]
```

Blog doc:

```
_id: “uuiduuiduuiduuid"
name: “Some interesting things I think”
```

I want to reverse populate the `authored_by` field in my Blog, so I reverse populate Authors specifying ‘blogs’ as the idField.

I want to end up with a Blog doc like

```
_id: “uuiduuiduuiduuid"
name: “Some interesting things I think”
authored_by: {_id: “uuiduuiduuiduuid", name: “Dave”, blogs: [“Some interesting things I think”]}
```

Assuming the example above is correct, my question would be, what would be the reason to store the blog `name` against the author rather than the Blog `_id` ? With the `_id` you can always access the the blog `name` via populating.

**Comment by moll** [comment]
FYI all: `.idea`s and `.*~`s and others go to your global `.gitignore`, not into individual projects' `.gitignores`. ;)

**Pull request closed without merging**
